[package]
name = "sludge"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
lazy_static = "1.5.0"
pest = "2.8.2"
pest_derive = "2.8.2"
serde = { version = "1.0.226", features = ["derive"] }
serde_json = "1.0.145"
